import type { StyleSpecification } from "maplibre-gl";
import type { StackStatus } from "./types";

export const SPB_CENTER: [number, number] = [30.3351, 59.9343];

export const DASH_SEQUENCE = [
  [0, 4, 3], [0.5, 4, 2.5], [1, 4, 2], [1.5, 4, 1.5],
  [2, 4, 1], [2.5, 4, 0.5], [3, 4, 0],
  [0, 0.5, 3, 3.5], [0, 1, 3, 3], [0, 1.5, 3, 2.5],
  [0, 2, 3, 2], [0, 2.5, 3, 1.5], [0, 3, 3, 1], [0, 3.5, 3, 0.5],
];

const DEFAULT_TILE_URL = "/api/tiles/spb-lo";

export function buildStyle(stack: StackStatus | null): StyleSpecification {
  const isVector = stack === null || stack?.basemap.source === "pmtiles_martin";
  if (isVector) {
    const rawUrl = stack?.basemap.url ?? DEFAULT_TILE_URL;
    const tileBase = `${window.location.origin}${rawUrl}`;
    return {
      version: 8 as const,
      glyphs: "/api/tiles/font/{fontstack}/{range}.pbf?v=2",
      sources: {
        basemap: {
          type: "vector" as const,
          tiles: [`${tileBase}/{z}/{x}/{y}`],
          minzoom: 5,
          maxzoom: 14,
        },
        "selected-building": {
          type: "geojson" as const,
          data: { type: "FeatureCollection", features: [] },
        },
        "delivery-mask": {
          type: "geojson" as const,
          data: { type: "FeatureCollection", features: [] },
        },
      },
      layers: [
        { id: "background", type: "background" as const, paint: { "background-color": "#0e1116" } },
        {
          id: "delivery-outside-mask",
          type: "fill" as const,
          source: "delivery-mask",
          paint: { "fill-color": "#0e1116", "fill-opacity": 1 },
        },
        {
          id: "landuse",
          type: "fill" as const,
          source: "basemap",
          "source-layer": "osm",
          filter: ["has", "landuse"],
          paint: {
            "fill-color": [
              "match", ["get", "landuse"],
              ["park", "forest", "recreation_ground", "grass", "meadow", "village_green", "allotments"], "#0d2218",
              ["industrial", "commercial", "retail", "construction"], "#15181f",
              ["residential", "farmyard"], "#12161e",
              "#1a2030",
            ],
            "fill-opacity": 0.75,
          },
        },
        {
          id: "parks-fill",
          type: "fill" as const,
          source: "basemap",
          "source-layer": "osm",
          filter: [
            "in", ["get", "landuse"],
            ["literal", ["park", "forest", "recreation_ground", "grass", "meadow", "village_green", "allotments"]],
          ],
          paint: { "fill-color": "#0d2318", "fill-opacity": 0.85 },
        },
        {
          id: "water-fill",
          type: "fill" as const,
          source: "basemap",
          "source-layer": "osm",
          filter: [
            "any",
            ["==", ["get", "natural"], "water"],
            ["==", ["get", "landuse"], "reservoir"],
            ["==", ["get", "waterway"], "riverbank"],
            ["==", ["get", "water"], "river"],
          ],
          paint: { "fill-color": "#0a1f3a", "fill-opacity": 1 },
        },
        {
          id: "waterway",
          type: "line" as const,
          source: "basemap",
          "source-layer": "osm",
          filter: ["in", ["get", "waterway"], ["literal", ["river", "canal", "stream"]]],
          layout: { "line-cap": "round" as const },
          paint: {
            "line-color": "#0a1f3a",
            "line-width": ["interpolate", ["linear"], ["zoom"], 8, 1.5, 12, 4, 16, 9],
          },
        },
        {
          id: "buildings",
          type: "fill" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 13,
          filter: ["has", "building"],
          paint: {
            "fill-color": [
              "interpolate", ["linear"],
              ["coalesce", ["to-number", ["get", "building:levels"]], 1],
              1, "#252a36", 3, "#2f3548", 6, "#3d4360", 10, "#525984", 16, "#6b6fa3", 25, "#8a8bc4",
            ],
            "fill-outline-color": "#1a1f2c",
            "fill-opacity": ["interpolate", ["linear"], ["zoom"], 13, 0.7, 16, 1],
          },
        },
        {
          id: "buildings-outline",
          type: "line" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 14,
          maxzoom: 16,
          filter: ["has", "building"],
          paint: {
            "line-color": "#0e1116",
            "line-width": ["interpolate", ["linear"], ["zoom"], 14, 0.4, 16, 1],
            "line-opacity": ["interpolate", ["linear"], ["zoom"], 14, 0.6, 15.5, 1, 16, 0],
          },
        },
        {
          id: "buildings-3d",
          type: "fill-extrusion" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 13,
          filter: ["all", ["has", "building"], ["==", ["geometry-type"], "Polygon"]],
          paint: {
            "fill-extrusion-color": [
              "interpolate", ["linear"],
              ["coalesce", ["to-number", ["get", "building:levels"]], 1],
              1, "#2a2f3d", 3, "#353b50", 6, "#444b6c", 10, "#5a6193", 16, "#7478b5", 25, "#9495cf",
            ],
            "fill-extrusion-height": ["*", ["coalesce", ["to-number", ["get", "building:levels"]], 1], 3],
            "fill-extrusion-base": ["coalesce", ["to-number", ["get", "min_height"]], 0],
            "fill-extrusion-opacity": 0.92,
            "fill-extrusion-vertical-gradient": true,
          },
        },
        {
          id: "footways",
          type: "line" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 15,
          filter: ["in", ["get", "highway"], ["literal", ["footway", "path", "pedestrian", "steps"]]],
          paint: {
            "line-color": "#4a6080",
            "line-width": ["interpolate", ["linear"], ["zoom"], 15, 1.0, 18, 2.5],
            "line-dasharray": [3, 1.5],
          },
        },
        {
          id: "cycleways-glow",
          type: "line" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 14,
          filter: ["any", ["==", ["get", "highway"], "cycleway"], ["==", ["get", "bicycle"], "designated"], ["==", ["get", "cycleway"], "lane"]],
          layout: { "line-cap": "round" as const },
          paint: {
            "line-color": "#22c55e",
            "line-width": ["interpolate", ["linear"], ["zoom"], 14, 6, 16, 10, 18, 14],
            "line-opacity": 0.12,
            "line-blur": 3,
          },
        },
        {
          id: "cycleways",
          type: "line" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 13,
          filter: ["any", ["==", ["get", "highway"], "cycleway"], ["==", ["get", "bicycle"], "designated"], ["==", ["get", "cycleway"], "lane"]],
          layout: { "line-cap": "round" as const },
          paint: {
            "line-color": "#22c55e",
            "line-width": ["interpolate", ["linear"], ["zoom"], 13, 1.2, 16, 3.5, 18, 5],
          },
        },
        {
          id: "roads-minor-casing",
          type: "line" as const,
          source: "basemap",
          "source-layer": "osm",
          filter: ["in", ["get", "highway"], ["literal", ["residential", "service", "unclassified", "tertiary", "tertiary_link", "living_street"]]],
          layout: { "line-cap": "round" as const, "line-join": "round" as const },
          paint: {
            "line-color": "#0c0f16",
            "line-width": ["interpolate", ["linear"], ["zoom"], 11, 1.5, 15, 5, 17, 9],
          },
        },
        {
          id: "roads-major-casing",
          type: "line" as const,
          source: "basemap",
          "source-layer": "osm",
          filter: ["in", ["get", "highway"], ["literal", ["primary", "primary_link", "secondary", "secondary_link", "trunk", "trunk_link", "motorway", "motorway_link"]]],
          layout: { "line-cap": "round" as const, "line-join": "round" as const },
          paint: {
            "line-color": "#080c12",
            "line-width": ["interpolate", ["linear"], ["zoom"], 9, 2, 13, 7, 16, 14],
          },
        },
        {
          id: "roads-minor",
          type: "line" as const,
          source: "basemap",
          "source-layer": "osm",
          filter: ["in", ["get", "highway"], ["literal", ["residential", "service", "unclassified", "tertiary", "tertiary_link", "living_street"]]],
          layout: { "line-cap": "round" as const, "line-join": "round" as const },
          paint: {
            "line-color": ["match", ["get", "highway"], ["service"], "#2e4060", ["living_street"], "#3a4a5c", "#4a5e7a"],
            "line-width": ["interpolate", ["linear"], ["zoom"], 11, 0.8, 15, 3.5, 17, 7],
          },
        },
        {
          id: "roads-major",
          type: "line" as const,
          source: "basemap",
          "source-layer": "osm",
          filter: ["in", ["get", "highway"], ["literal", ["primary", "primary_link", "secondary", "secondary_link", "trunk", "trunk_link", "motorway", "motorway_link"]]],
          layout: { "line-cap": "round" as const, "line-join": "round" as const },
          paint: {
            "line-color": ["match", ["get", "highway"], ["motorway", "motorway_link", "trunk", "trunk_link"], "#7090c0", "#6090c0"],
            "line-width": ["interpolate", ["linear"], ["zoom"], 9, 1.2, 13, 5.5, 16, 13],
          },
        },
        {
          id: "bridges-casing",
          type: "line" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 12,
          filter: ["all", ["has", "highway"], ["==", ["get", "bridge"], "yes"]],
          layout: { "line-cap": "butt" as const },
          paint: {
            "line-color": "#050810",
            "line-width": ["interpolate", ["linear"], ["zoom"], 12, 4, 16, 13],
          },
        },
        {
          id: "bridges",
          type: "line" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 12,
          filter: ["all", ["has", "highway"], ["==", ["get", "bridge"], "yes"]],
          layout: { "line-cap": "butt" as const },
          paint: {
            "line-color": "#7a90b2",
            "line-width": ["interpolate", ["linear"], ["zoom"], 12, 2, 16, 10],
          },
        },
        {
          id: "passages",
          type: "line" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 14,
          filter: ["any", ["==", ["get", "tunnel"], "building_passage"], ["all", ["==", ["get", "highway"], "footway"], ["==", ["get", "tunnel"], "yes"]], ["==", ["get", "covered"], "arcade"]],
          paint: {
            "line-color": "#ffd166",
            "line-width": ["interpolate", ["linear"], ["zoom"], 14, 2, 17, 4, 18, 6],
            "line-dasharray": [2.5, 1],
          },
        },
        {
          id: "bridge-labels",
          type: "symbol" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 13,
          filter: ["all", ["has", "name"], ["==", ["get", "bridge"], "yes"]],
          layout: {
            "symbol-placement": "line" as const,
            "text-field": ["coalesce", ["get", "name:ru"], ["get", "name"]] as never,
            "text-font": ["Noto Sans Bold"],
            "text-size": ["interpolate", ["linear"], ["zoom"], 13, 11, 17, 15],
            "text-letter-spacing": 0.04,
            "symbol-spacing": 400,
          },
          paint: { "text-color": "#e8edf3", "text-halo-color": "#0e1116", "text-halo-width": 2 },
        },
        {
          id: "water-labels",
          type: "symbol" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 10,
          filter: ["all", ["has", "name"], ["any", ["==", ["get", "natural"], "water"], ["in", ["get", "waterway"], ["literal", ["river", "canal", "stream"]]], ["==", ["get", "waterway"], "riverbank"]]],
          layout: {
            "symbol-placement": "line" as const,
            "text-field": ["coalesce", ["get", "name:ru"], ["get", "name"]] as never,
            "text-font": ["Noto Sans Regular"],
            "text-size": ["interpolate", ["linear"], ["zoom"], 10, 11, 14, 15, 17, 18],
            "text-letter-spacing": 0.05,
            "symbol-spacing": 350,
          },
          paint: { "text-color": "#3a7ab5", "text-halo-color": "#060b14", "text-halo-width": 2 },
        },
        {
          id: "road-labels-major",
          type: "symbol" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 12,
          filter: ["all", ["has", "name"], ["in", ["get", "highway"], ["literal", ["primary", "primary_link", "secondary", "secondary_link", "trunk", "trunk_link", "motorway", "motorway_link"]]]],
          layout: {
            "symbol-placement": "line" as const,
            "text-field": ["coalesce", ["get", "name:ru"], ["get", "name"]] as never,
            "text-font": ["Noto Sans Bold"],
            "text-size": ["interpolate", ["linear"], ["zoom"], 12, 11, 17, 15],
            "text-letter-spacing": 0.05,
            "symbol-spacing": 280,
          },
          paint: { "text-color": "#e8edf3", "text-halo-color": "#0e1116", "text-halo-width": 2 },
        },
        {
          id: "road-labels-minor",
          type: "symbol" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 13,
          filter: ["all", ["has", "name"], ["in", ["get", "highway"], ["literal", ["residential", "service", "unclassified", "tertiary", "tertiary_link", "living_street"]]]],
          layout: {
            "symbol-placement": "line" as const,
            "text-field": ["coalesce", ["get", "name:ru"], ["get", "name"]] as never,
            "text-font": ["Noto Sans Regular"],
            "text-size": ["interpolate", ["linear"], ["zoom"], 14, 11, 18, 14],
            "text-letter-spacing": 0.05,
            "symbol-spacing": 250,
          },
          paint: { "text-color": "#cfd6dc", "text-halo-color": "#0e1116", "text-halo-width": 1.6 },
        },
        {
          id: "place-labels",
          type: "symbol" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 9,
          maxzoom: 15,
          filter: ["all", ["has", "name"], ["in", ["get", "place"], ["literal", ["city", "town", "village", "suburb", "neighbourhood", "quarter"]]]],
          layout: {
            "text-field": ["coalesce", ["get", "name:ru"], ["get", "name"]] as never,
            "text-font": ["Noto Sans Bold"],
            "text-size": [
              "interpolate", ["linear"], ["zoom"],
              9, ["match", ["get", "place"], "city", 14, "town", 12, "village", 10, "suburb", 11, 9],
              14, ["match", ["get", "place"], "city", 22, "town", 18, "village", 14, "suburb", 16, 13],
            ],
            "text-letter-spacing": 0.08,
            "text-transform": "uppercase",
          },
          paint: {
            "text-color": "#a8b2c0",
            "text-halo-color": "#0e1116",
            "text-halo-width": 2,
            "text-opacity": ["interpolate", ["linear"], ["zoom"], 9, 1, 14, 0.8, 15, 0],
          },
        },
        {
          id: "metro-stations",
          type: "symbol" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 10,
          filter: ["any", ["==", ["get", "station"], "subway"], ["all", ["==", ["get", "railway"], "station"], ["==", ["get", "subway"], "yes"]], ["all", ["==", ["get", "railway"], "station"], ["==", ["get", "network"], "Петербургский метрополитен"]]],
          layout: {
            "icon-image": "metro-icon",
            "icon-size": ["interpolate", ["linear"], ["zoom"], 10, 0.55, 13, 0.75, 16, 1.0],
            "icon-anchor": "center" as const,
            "icon-allow-overlap": true,
            "icon-ignore-placement": false,
            "text-field": ["coalesce", ["get", "name:ru"], ["get", "name"]] as never,
            "text-font": ["Noto Sans Bold"],
            "text-anchor": "top" as const,
            "text-offset": [0, 0.95],
            "text-size": ["interpolate", ["linear"], ["zoom"], 10, 10, 13, 12, 16, 14],
            "text-optional": true,
            "text-max-width": 10,
          },
          paint: { "text-color": "#e05050", "text-halo-color": "#0a0d12", "text-halo-width": 2 },
        },
        {
          id: "metro-entrances",
          type: "symbol" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 14,
          filter: ["==", ["get", "railway"], "subway_entrance"],
          layout: {
            "icon-image": "metro-entrance-icon",
            "icon-size": ["interpolate", ["linear"], ["zoom"], 14, 0.6, 17, 0.9],
            "icon-anchor": "center" as const,
            "icon-allow-overlap": true,
            "text-field": ["get", "ref"] as never,
            "text-font": ["Noto Sans Bold"],
            "text-anchor": "top" as const,
            "text-offset": [0, 0.75],
            "text-size": 10,
            "text-optional": true,
          },
          paint: { "text-color": "#e05050", "text-halo-color": "#0a0d12", "text-halo-width": 1.5 },
        },
        {
          id: "housenumbers",
          type: "symbol" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 15,
          filter: ["all", ["has", "addr:housenumber"], ["==", ["geometry-type"], "Polygon"], ["!", ["has", "building:part"]], ["!=", ["get", "building"], "garage"], ["!=", ["get", "building"], "garages"], ["!=", ["get", "building"], "shed"], ["!=", ["get", "building"], "roof"], ["!=", ["get", "building"], "carport"]],
          layout: {
            "text-field": ["get", "addr:housenumber"],
            "text-font": ["Noto Sans Bold"],
            "text-size": ["interpolate", ["linear"], ["zoom"], 15, 10, 17, 15, 19, 20],
            "text-padding": 4,
            "text-allow-overlap": ["step", ["zoom"], false, 17, true],
            "text-ignore-placement": false,
            "symbol-placement": "point",
          },
          paint: {
            "text-color": "#ffd166",
            "text-halo-color": "#0e1116",
            "text-halo-width": ["interpolate", ["linear"], ["zoom"], 15, 2, 17, 3],
            "text-halo-blur": 0.4,
            "text-opacity": ["interpolate", ["linear"], ["zoom"], 15, 0.8, 16, 1],
          },
        },
        {
          id: "selected-building-3d",
          type: "fill-extrusion" as const,
          source: "selected-building",
          paint: {
            "fill-extrusion-color": "#fb923c",
            "fill-extrusion-height": ["max", ["*", ["coalesce", ["to-number", ["get", "building:levels"]], 1], 3], 8],
            "fill-extrusion-base": ["coalesce", ["to-number", ["get", "min_height"]], 0],
            "fill-extrusion-opacity": 1,
            "fill-extrusion-vertical-gradient": false,
          },
        },
        {
          id: "selected-building-outline",
          type: "line" as const,
          source: "selected-building",
          paint: { "line-color": "#fde047", "line-width": 3.5, "line-blur": 0.3 },
        },
        {
          id: "crossings",
          type: "symbol" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 16,
          filter: ["any", ["==", ["get", "highway"], "crossing"], ["==", ["get", "footway"], "crossing"], ["has", "crossing"]],
          layout: {
            "icon-image": "zebra-icon",
            "icon-size": ["interpolate", ["linear"], ["zoom"], 16, 0.55, 18, 0.85, 20, 1.15],
            "icon-rotation-alignment": "viewport",
            "icon-pitch-alignment": "viewport",
            "icon-allow-overlap": true,
            "icon-ignore-placement": true,
          },
        },
        {
          id: "building-labels",
          type: "symbol" as const,
          source: "basemap",
          "source-layer": "osm",
          minzoom: 16,
          filter: ["all", ["has", "name"], ["has", "building"]],
          layout: {
            "text-field": ["coalesce", ["get", "name:ru"], ["get", "name"]] as never,
            "text-font": ["Noto Sans Regular"],
            "text-size": ["interpolate", ["linear"], ["zoom"], 16, 10, 19, 13],
            "text-max-width": 8,
            "text-padding": 4,
          },
          paint: { "text-color": "#9aa7c2", "text-halo-color": "#0e1116", "text-halo-width": 1.4 },
        },
      ],
    };
  }
  return {
    version: 8 as const,
    glyphs: "/api/tiles/font/{fontstack}/{range}.pbf?v=2",
    sources: {
      "raster-dark": {
        type: "raster" as const,
        tiles: ["https://basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png"],
        tileSize: 256,
        attribution: "© OpenStreetMap contributors © CARTO",
        maxzoom: 19,
      },
    },
    layers: [
      { id: "background", type: "background" as const, paint: { "background-color": "#0d0e12" } },
      { id: "raster", type: "raster" as const, source: "raster-dark", paint: { "raster-opacity": 0.97 } },
    ],
  };
}
