// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/map-improvements/CyclewaysAndStreets.tsx": () => import("../components/mockups/map-improvements/CyclewaysAndStreets.tsx"),
  "./components/mockups/map-improvements/HouseNumbersAndLabels.tsx": () => import("../components/mockups/map-improvements/HouseNumbersAndLabels.tsx"),
  "./components/mockups/map-improvements/YardsAndFootways.tsx": () => import("../components/mockups/map-improvements/YardsAndFootways.tsx")
};
